from brownie import Airdrop, ERC20, accounts, Contract

def main():
    acct = accounts.load("myaccount")
    for i in range(7):
        SOMM_ADDRESS = ERC20.deploy("Test ERC20", "T20", {"from": acct})
        DURATION = 60 * 60 * 24 * 30 * 3 # 3 months
        AIRDROP_ADDRESS = Airdrop.deploy(SOMM_ADDRESS, 0x23e8b2aab9ad8a3552bab04132fc4e41579d5b4a4cc6ca6836823e5be5b1e66a, acct, DURATION, {"from": acct})
        SOMM_ADDRESS.transfer(AIRDROP_ADDRESS, 5 * 10 ** 6 * 10 ** 18, {"from": acct})

# def main():
#     acct = accounts.load("myaccount")
#     SOMM_ADDRESS = Contract.from_abi("Token", "0xf4Ce3Bec7F39ef21802f6161191CAA9a19C1D51B", [{"anonymous":False,"inputs":[{"indexed":True,"name":"_from","type":"address"},{"indexed":True,"name":"_to","type":"address"},{"indexed":False,"name":"_value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"_owner","type":"address"},{"indexed":True,"name":"_spender","type":"address"},{"indexed":False,"name":"_value","type":"uint256"}],"name":"Approval","type":"event"},{"inputs":[{"name":"name_","type":"string"},{"name":"symbol_","type":"string"}],"outputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint256"}],"stateMutability":"pure","type":"function"},{"inputs":[{"name":"recipient","type":"address"},{"name":"amount","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"sender","type":"address"},{"name":"recipient","type":"address"},{"name":"amount","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"arg0","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"name":"arg0","type":"address"},{"name":"arg1","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"}])
#     DURATION = 60 * 60 * 24 * 30 * 6 # 6 months
#     AIRDROP_ADDRESS = Contract.from_abi("Airdrop", "0xf9cA00A14e0D2CA9780790bac886e801Bb9cF969", [{"inputs":[{"name":"_somm_token","type":"address"},{"name":"_merkle_root","type":"bytes32"},{"name":"_gravity_bridge","type":"address"},{"name":"_duration","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"somm_token","outputs":[{"name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"gravity_bridge","outputs":[{"name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"merkle_root","outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"deadline","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"name":"receiver","type":"address"},{"name":"amount","type":"uint256"},{"name":"merkle_proof","type":"bytes32[15]"}],"name":"claim","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"return_token","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"arg0","type":"address"}],"name":"received","outputs":[{"name":"","type":"bool"}],"stateMutability":"view","type":"function"}])
#     SOMM_ADDRESS.transfer(AIRDROP_ADDRESS, 5 * 10 ** 6 * 10 ** 18, {"from": acct})